[sqlserver]
host = 192.168.210.60:1433
user = usrrepservices
pwd = Ill.niño
db = master
;psql postgresql://e_bvapy_test_17894530@bvapy-test-17894530.dev.odoo.com/bvapy-test-17894530
[xmlrpc]
host = https://bvapy.odoo.com
host_old = https://bolsadevalores.odoo.com
port = 443
db_old = interfacespy-bvpasa-odoo-addons-15-0-6076503
db = gcaceres93-bvapytest-main-14370389
user = admin
pwd = 3capzadmin

[xmlrpctest]
host = http://localhost
port = 8069
db = bolsaprod1
user = admin
pwd = 3capzadmin
