# -*- coding: utf-8 -*-
{
'name': 'Presales Ecoenergia',
'version': '1.0',
'category': 's',
'description': """Module for manage presales concept. 
""",
'author': 'SATI',
'website': 'http://www.sati.com.py',
'depends': ['base','stock','sale','sale_project','sale_management','crm','purchase', 'fleet','project','account', "mrp", "base_tier_validation","purchase_request"],
'data': [
        'security/security.xml',
        'views/crm_lead_view.xml',
        'views/presale_view.xml',
        'views/purchase_request_views.xml',
        'views/crm_team_view.xml',
        'views/product_view.xml',
        'views/sales_order.xml',
        'views/fleet_vehicle.xml',
        'views/presale_labor_type.xml',
        'views/presale_currency_rate.xml',
        'views/presale_working_rate.xml',
        'views/presale_logistic_type.xml',
        'views/presale_fuel_type.xml',
        'views/product_brand.xml',
        'views/presale_types_additionals.xml',
        'data/presale_sequece_data.xml',
        'views/menus.xml',
        'report/reports.xml',
        'report/preventa_informe.xml',
        'security/ir.model.access.csv',
        'report/registrar_pago_oculto.xml',
],
'installable': True,
    'auto_install': False,
    'application': True,

}
